version: '3.8'

networks:
  sql_agent_network:
    driver: bridge

volumes:
  n8n_sql_data:
  postgres_data:
  ollama_data:
  # Hemos eliminado pgadmin_data de aquí

services:
  # 1. n8n - Orquestador de flujos
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_sql
    restart: unless-stopped
    ports:
      - "5679:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5679/
      - GENERIC_TIMEZONE=America/Lima
    volumes:
      - n8n_sql_data:/home/node/.n8n
      # ¡NUEVA RUTA AQUÍ! Mapeamos tu carpeta a la ruta permitida por n8n
      - ./:/home/node/.n8n-files
    networks:
      - sql_agent_network

  # 2. PostgreSQL - Base de datos para los Excels
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=analytics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sql_agent_network

  # 3. pgAdmin - Navegador Web para Postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    # Hemos eliminado el volume de pgadmin para que levante sin error 404
    networks:
      - sql_agent_network


  # 4. Ollama - Motor LLM Local
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_sql
    restart: unless-stopped
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    devices:
      - /dev/dri:/dev/dri
    environment:
      - OLLAMA_VULKAN=1
      - OLLAMA_DEBUG=1
    networks:
      - sql_agent_network
